---
AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation for EC2 Security Groups.
Parameters:
  VpcId:
    Type: String
    Description: VPC id
  VpcSubnet:
    Description: Network CIDR
    Type: String
Resources:
  HttpsHttpSshAll:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http and https from client
      VpcId:
        Fn::ImportValue:
          Ref: VpcId
      # HTTP is allowed from anywhere    
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      # HTTPS is allowed from anywhere   
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
      # SSH is allowed from anywhere
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0        
      Tags:
      - Key: Name
        Value: HttpsHttpSshAll

Outputs:
  HttpsHttpSshAll:
    Value:
      Ref: HttpsHttpSshAll
    Export:
      Name: !Join [ "-", [ !Ref "AWS::StackName", HttpsHttpSshAll ] ]  
